language: node_js

node_js:
    - 4.1.1
    - 0.11
    - 0.10

before_install:
    - gem install sass
    - npm install -g bower
    - npm install -g gulp

before_script:
    - npm install
    - bower install

script:
    - gulp frontsize:build
    - cd ./test
    - gulp frontsize:css
    - cd ../
    - mv a-pollo.yml _original_a-pollo.yml
    - mv a-pollo.travis.yml a-pollo.yml
    - node index.js
